[theme]
name = "slick"
[icons]
name = "awesome5"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
ap_format = "{strength} {ssid}"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = false
show_temperature = false
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 5

[[block]]
block = "time"
interval = 1
format = "%H:%M:%S %Y-%m-%d"
