exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland XDG_SESSION_TYPE=wayland QT_QPA_PLATFORM=wayland GDK_BACKEND=wayland SDL_VIDEODRIVER=wayland MOZ_ENABLE_WAYLAND=1 ELECTRON_OZONE_PLATFORM_HINT=wayland OZONE_PLATFORM=wayland
exec-once = systemctl --user start graphical-session.target xdg-desktop-portal.service xdg-desktop-portal-gtk.service
exec-once = hypridle & mako & waybar
exec-once = swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-clip-persist --clipboard regular & clipse -listen
exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace &
exec-once=fcitx5-remote -r
