# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = windowrule-1
  suppress_event = maximize
  opacity = 1 1
  match:class = .*
}


# Force chromium into a tile to deal with --app bug
windowrule {
  name = windowrule-2
  tile = on
  match:class = ^(Chromium)$
}


# Float sound and bluetooth settings
windowrule {
  name = windowrule-3
  float = on
  match:class = ^(org.pulseaudio.pavucontrol|blueberry.py)$
}



# Just dash of opacity

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-4
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Proper background blur for wofi
layerrule {
  name = layerrule-1
  blur = on
  match:namespace = wofi
}


# Float in the middle for clipse clipboard manager
windowrule {
  name = windowrule-5
  float = on
  size = 622 652
  stay_focused = on
  match:class = (clipse)
}
